version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_hibernate
    environment:
      POSTGRES_USER: hibernate_user
      POSTGRES_PASSWORD: hibernate_pass
      POSTGRES_DB: hibernate_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
